baseURL: https://psycorona.org/
languageCode: en-us
title: Psychology Corona
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Translation key changes word for Navbar item for translations
  translationKey: Language
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: Give us your thoughts about the pandemic –Participate in our intensive survey (20 minutes)
  navbarlogo:
  # Logo (from static/images/___)
    #image: coronavirus.png
    #link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    #Some arbitray key is necessary for underlying template to render
    #Since we only soft copy the template from gitHub i cannot make changes to it
    alternative: true
    # Main hero title
    #title: Psychology Corona Study
    # Hero subtitle (optional)
    #subtitle: Global study of effects of COVID-19
    # Button text
    #buttontext: Take 20-minute survey
    # Where the main hero button links to
    #buttonlink: "https://rug.eu.qualtrics.com/jfe/form/SV_8wUo0naXXVAlB2t?fbclid=IwAR2K5PTfKXmekrvDaiTkH8CJ0CC27TwP4LU0pIBA5_TbWYtiGtc7HHz4xAE"
    # Hero image (from static/images/___)
    #image: coronavirus.png
    # Footer logos (from static/images/logos/clients/___.svg)
    #clientlogos:
    #- university-nyu
    #- university-groningen

  heroTitle: Psychology Corona Study
  heroSubtitle: Global study of effects of COVID-19
  heroButtontext: Take 20-minute survey
  heroButtonlink: "https://rug.eu.qualtrics.com/jfe/form/SV_8wUo0naXXVAlB2t?fbclid=IwAR2K5PTfKXmekrvDaiTkH8CJ0CC27TwP4LU0pIBA5_TbWYtiGtc7HHz4xAE"
  heroImage: coronavirus.png
  heroClientlogos:
    - university-nyu
    - university-groningen

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /
  - title: About This Study
    url: /about/
  - title: Press
    url: /press/
  - title: Data
    url: /data/
  - title: FAQ
    url: /faq/
  - title: Team
    url: /team/

  # Extended section 5 styling
  section5: true
  contactInvitation1: Reach out to us
  contactInvitation2: We'd love to hear from you
  contactButton: Contact Us

  footer:
    #Some arbitray key is necessary for underlying template to render
    #Since we only soft copy the template from gitHub i cannot make changes to it
    alternative: true 
    # Logo (from /images/logos/___)
    # Social Media Title
    #socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    #socialmedia:
    #- link: https://github.com/simabasel/psycorona
      # Icons are from Font Awesome
    #  icon: github
    #- link: https://www.facebook.com/Covid-19-Research-Study-110600253911208/
    #  icon: facebook

  footerSocialmediatitle: Follow Us
  footerSocialmedia:
    - link: https://github.com/simabasel/psycorona
      # Icons are from Font Awesome
      icon: github
    - link: https://www.facebook.com/Covid-19-Research-Study-110600253911208/
      icon: facebook
  
#Languages. Since I redefined each of the keys for footer & hero to be
#non-nested regular parameters the parameter change definition is much shorter.
#if one would use the original indexed version one would have to redefine the key
#value pair for non-repetitive parts for every language as well, including links, images, etc.
#This workaround makes sure that only the parts that actually need to change are necessary to change

languages:
  en:
    contentDir: content/english
    languageName: English
    weight: 1
  de:
    contentDir: content/german
    languageName: Deutsch
    weight: 2
    description: An der 20 minütigen Studie teilnehmen
    title:  Psychologie Corona Studie
    translationKey: Übersetzungen
    navbar:
    - title: Über diese Studie
      url: /über-die-studie/
    - title: Presse
      url: /presse/
    - title: Daten
      url: /daten/
    - title: FAQ
      url: /faq/
    - title: Team
      url: /team/
    heroTitle: Psychologie Corona Studie
    heroSubtitle: Globale Studie über die Auswirkungen von Covid-19
    heroButtontext: Zur Studie
    contactInvitation1: Kontaktieren Sie Uns
    contactInvitation2: Wir freuen uns von Ihnen zu hören
    contactButton: Kontakt aufnehmen
    footerSocialmediatitle: Folge uns
